### ISSUE TITLE
Dashboard Updates

### ISSUE THREAD

**Issue by fbausch** [simra-project/simra-project.github.io#4]
The dashboard data and incident map data is not updated in a consistent way.

For example, the Mannheim/Heidelberg got updated data a long time ago - since then the actual data is not updated. However, the Mannheim-meta.json (https://github.com/simra-project/simra-project.github.io/blob/master/region/Mannheim-meta.json) gets updated every Sunday saying "Karte generiert am <last sunday>".

This gives the wrong impression that the displayed data includes recent events.

One possible fix:
- Actually update the map data. (I would prefer this.)

Another possible fix:
- Don't update the meta info as long as there is no actual update of the map data.

**Comment by selphiron** [comment]
Thanks for the info, there was a problem with the cron jobs and I fixed them. The dashboard and map data are updated regularly again.
